package com.pointblue.dirxml.sim;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

import static org.junit.Assert.*;

/** The case.properties propagated into harvested cases. No DB/engine needed. */
public class HarvesterTest {

    @Rule
    public TemporaryFolder tmp = new TemporaryFolder();

    private static Properties props(String... kv) {
        Properties p = new Properties();
        for (int i = 0; i < kv.length; i += 2) {
            p.setProperty(kv[i], kv[i + 1]);
        }
        return p;
    }

    /** A config dir holding a real export file at {@code rel}, so path-rewrite triggers. */
    private Path cfgDirWith(String rel) throws Exception {
        Path dir = tmp.newFolder("harvest").toPath();
        Path f = dir.resolve(rel).normalize();
        Files.createDirectories(f.getParent());
        Files.writeString(f, "<driver-configuration/>");
        return dir;
    }

    @Test
    public void dropsEventSourceKeysKeepsConfigKeys() throws Exception {
        Path dir = cfgDirWith("CyberArk.xml");
        Properties cfg = props(
            "db", "jdbc:postgresql://h/idm", "dbUser", "u", "dbPassword", "s",
            "eventType", "modify", "eventsDriver", "cn=AD,o=s", "eventLimit", "50",
            "export", "CyberArk.xml", "channel", "subscriber", "driver", "CyberArk");
        String out = Harvester.propagatedProps(dir, cfg);

        assertFalse("source key dropped", out.contains("db="));
        assertFalse(out.contains("eventType="));
        assertFalse(out.contains("eventsDriver="));
        assertFalse(out.contains("dbPassword="));
        assertTrue("config kept", out.contains("channel=subscriber"));
        assertTrue(out.contains("driver=CyberArk"));
    }

    @Test
    public void rewritesExistingConfigSourcePathToAbsolute() throws Exception {
        Path dir = cfgDirWith("driver-config/CyberArk.xml");
        Properties cfg = props("db", "jdbc:postgresql://h/idm",
            "export", "driver-config/CyberArk.xml", "channel", "subscriber");
        String out = Harvester.propagatedProps(dir, cfg);

        assertTrue(out.contains("export=" + dir.resolve("driver-config/CyberArk.xml")));
        assertFalse("not the relative form", out.contains("export=driver-config/"));
    }

    @Test
    public void leavesSchemaSentinelAndLiveValuesVerbatim() throws Exception {
        Path dir = tmp.newFolder("h").toPath();   // no on-disk export
        Properties cfg = props("db", "x", "channel", "subscriber",
            "schema", "ldap", "ldapConfig", "cn=driverset1,o=system");
        String out = Harvester.propagatedProps(dir, cfg);

        assertTrue("sentinel kept", out.contains("schema=ldap"));
        assertTrue("live DN kept", out.contains("ldapConfig=cn=driverset1,o=system"));
    }

    @Test
    public void copiesConnectionKeysVerbatim() throws Exception {
        Path dir = cfgDirWith("d.xml");
        Properties cfg = props("db", "jdbc:postgresql://h/idm",
            "export", "d.xml", "channel", "subscriber",
            "ldap", "ldaps://host:636", "ldapBindDn", "cn=admin", "namedPassword.app", "x");
        String out = Harvester.propagatedProps(dir, cfg);

        assertTrue(out.contains("ldap=ldaps://host:636"));
        assertTrue(out.contains("ldapBindDn=cn=admin"));
        assertTrue(out.contains("namedPassword.app=x"));
    }

    @Test
    public void carriesAProvenanceHeader() throws Exception {
        String out = Harvester.propagatedProps(tmp.newFolder("h").toPath(),
            props("db", "x", "channel", "subscriber"));
        assertTrue(out.startsWith("# generated by `sim harvest`"));
        assertTrue(out.contains("change detector"));
    }
}
